import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { OrderQuote, SparePart, StockMovement, User, Vehicle, WorkOrder, WorkOrderStatus } from '../../models/workshop.models';
import { WorkshopService } from '../../core/services/workshop.service';
import { FieldErrors, cleanEmail, cleanRut, cleanText, formatRut, normalizePlate, validChileanMobile, validEmail, validFullName, validNamePart, validPlate, validRut } from '../../core/utils/reception.validators';

type Section = 'inicio' | 'checkin' | 'ordenes' | 'clientes' | 'vehiculos' | 'citas' | 'entregas' | 'inventario';
@Component({ selector: 'app-receptionist-dashboard', standalone: true, imports: [CommonModule, FormsModule, RouterLink], templateUrl: './receptionist-dashboard.component.html', styleUrls: ['./receptionist-dashboard.component.css', './receptionist-dashboard.logout.css'] })
export class ReceptionistDashboardComponent {
  section: Section = 'inicio'; searchTerm = ''; selectedVehicleId = 0; selectedOrderId = 0; showClientModal = false; showVehicleModal = false;
  message = ''; messageType: 'success' | 'error' = 'success'; credentials = signal<{ email: string; password: string } | null>(null); checkinCompleted = signal<number | null>(null); saving = false;
  clientErrors: FieldErrors = {}; clientSummary: string[] = []; vehicleErrors: FieldErrors = {}; checkinErrors: FieldErrors = {}; checkinSummary: string[] = []; quoteErrors: FieldErrors = {}; appointmentErrors: FieldErrors = {}; deliveryErrors: FieldErrors = {}; photoUrls: string[] = []; photoError = '';
  intake = { description: '', mileage: null as number | null, fuel: '1/2', damages: '', noDamages: false, notes: '', items: '', estimatedDate: '', mechanicId: 0, clientConfirmed: false };
  client = { id: 0, name: '', firstName: '', firstLastName: '', secondLastName: '', email: '', rut: '', phone: '', alternatePhone: '', dataConsent: false }; vehicle = { id: 0, ownerId: 0, type: 'Auto' as 'Auto' | 'Moto', brand: '', model: '', plate: '', year: new Date().getFullYear() }; quote = { parts: 0, labor: 0, other: 0, detail: '', channel: 'portal' as 'presencial' | 'whatsapp' | 'portal', rejectReason: '' }; appointment = { vehicleId: 0, description: '', date: '' };
  deliveryOrderId = 0; delivery = { receiverName: '', receiverRut: '', approved: false, signed: false };
  stockReceipt = { sparePartId: 0, quantity: 1, supplier: '', reference: '' };
  readonly nav: { id: Section; label: string; icon: string }[] = [{ id: 'inicio', label: 'Inicio', icon: '⌂' }, { id: 'checkin', label: 'Recepción / Check-in', icon: '↳' }, { id: 'ordenes', label: 'Órdenes', icon: '▤' }, { id: 'clientes', label: 'Clientes', icon: '♙' }, { id: 'vehiculos', label: 'Vehículos', icon: '▱' }, { id: 'citas', label: 'Citas', icon: '◷' }, { id: 'entregas', label: 'Entregas', icon: '✓' }, { id: 'inventario', label: 'Inventario', icon: '▦' }];
  constructor(public readonly workshop: WorkshopService, private readonly router: Router) { this.workshop.loadStockMovements(); }
  get clients(): User[] { return this.workshop.users().filter(u => u.role === 'cliente' && u.active !== false); } get mechanics(): User[] { return this.workshop.users().filter(u => u.role === 'mecanico' && u.active !== false); }
  get spareParts(): SparePart[] { return this.workshop.spareParts().filter(part => part.active !== false); } get stockMovements(): StockMovement[] { return this.workshop.stockMovements(); } get lowStockParts(): SparePart[] { return this.spareParts.filter(part => part.stock <= part.stockMinimo); }
  get vehicles(): Vehicle[] { const q = this.searchTerm.toLowerCase(); return this.workshop.vehicles().filter(v => v.active !== false && (!q || `${v.plate} ${v.brand} ${v.model} ${this.clientName(v.ownerId)}`.toLowerCase().includes(q))); }
  get selectedVehicle(): Vehicle | undefined { return this.workshop.vehicles().find(v => v.id === this.selectedVehicleId); } get selectedOrder(): WorkOrder | undefined { return this.workshop.orders().find(o => o.id === this.selectedOrderId); }
  get appointments(): WorkOrder[] { return this.workshop.orders().filter(o => o.status === 'solicitada'); } get deliveries(): WorkOrder[] { return this.workshop.orders().filter(o => o.status === 'listo_para_entrega' || o.status === 'trabajo_terminado'); }
  get sectionLabel(): string { return this.nav.find(item => item.id === this.section)?.label || 'Recepción'; }
  count(statuses: WorkOrderStatus[]): number { return this.workshop.orders().filter(o => statuses.includes(this.workshop.normalizeStatus(o.status))).length; } clientName(id: number): string { return this.workshop.users().find(u => u.id === id)?.name || 'Cliente'; } vehicleName(id: number): string { const v = this.workshop.vehicles().find(x => x.id === id); return v ? `${v.brand} ${v.model} · ${v.plate}` : 'Vehículo'; }
  statusLabel(status: WorkOrderStatus): string { return ({ solicitada: 'Cita agendada', recibido: 'Ingresado', en_diagnostico: 'En diagnóstico', cotizacion_pendiente: 'Esperando aprobación', esperando_aprobacion: 'Esperando aprobación', en_reparacion: 'En reparación', trabajo_terminado: 'Trabajo terminado', listo_para_entrega: 'Listo para retiro', entregado: 'Entregado', cerrado: 'Entregado' } as Record<string, string>)[this.workshop.normalizeStatus(status)] || status; }
  setSection(section: Section): void { this.section = section; this.message = ''; } logout(): void { this.workshop.logout(); this.router.navigate(['/login']); } selectVehicle(v: Vehicle): void { this.selectedVehicleId = v.id; }
  onPhotoSelected(event: Event): void {
    this.photoError = ''; const files = Array.from((event.target as HTMLInputElement).files || []);
    if (this.photoUrls.length + files.length > 6) { this.photoError = 'Puedes adjuntar un máximo de 5 fotos.'; return; }
    for (const file of files) {
      if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type) || file.size > 5 * 1024 * 1024) { this.photoError = 'Solo se aceptan JPG, PNG o WEBP de hasta 5 MB.'; continue; }
      const reader = new FileReader(); reader.onload = () => this.photoUrls.push(String(reader.result)); reader.readAsDataURL(file);
    }
  }
  removePhoto(index: number): void { this.photoUrls.splice(index, 1); }
  private validateCheckin(): boolean {
    const errors: FieldErrors = {}; const v = this.selectedVehicle; const today = new Date().toISOString().slice(0, 10);
    if (!v) errors.vehicle = 'Debes seleccionar un vehículo.';
    if (cleanText(this.intake.description, 500).length < 10) errors.description = 'El motivo debe tener al menos 10 caracteres.';
    if (this.intake.mileage === null || !Number.isInteger(Number(this.intake.mileage)) || Number(this.intake.mileage) < 0 || Number(this.intake.mileage) > 2_000_000) errors.mileage = 'Ingresa un kilometraje entero entre 0 y 2.000.000.';
    if (!this.intake.fuel) errors.fuel = 'Selecciona el nivel de combustible.';
    if (!this.intake.noDamages && !cleanText(this.intake.damages, 1000)) errors.damages = 'Describe los daños o marca “sin daños”.';
    if (!this.intake.estimatedDate || this.intake.estimatedDate < today) errors.estimatedDate = 'La fecha estimada no puede ser anterior a hoy.';
    if (!this.intake.clientConfirmed) errors.clientConfirmed = 'Se requiere la confirmación del cliente al ingreso.';
    if (v && this.workshop.orders().some(order => order.vehicleId === v.id && !['solicitada', 'listo', 'listo_para_entrega', 'entregado', 'cerrado', 'cancelado'].includes(order.status) && order.id !== this.selectedOrderId)) errors.vehicle = 'Este vehículo ya tiene un ingreso activo.';
    this.checkinErrors = errors;
    this.checkinSummary = Object.values(errors).filter((message): message is string => Boolean(message));
    return !this.checkinSummary.length;
  }
  submitCheckin(): void {
    if (!this.validateCheckin()) { this.notify('error', `No se pudo registrar la ficha: ${this.checkinSummary.join(' ')}`); return; } const v = this.selectedVehicle!; const mechanic = this.mechanics.find(m => m.id === Number(this.intake.mechanicId));
    const data = { entryMileage: this.intake.mileage!, fuelLevel: this.intake.fuel, receptionNotes: cleanText(this.intake.notes, 1000), damages: this.intake.noDamages ? 'Sin daños preexistentes declarados.' : cleanText(this.intake.damages, 1000), leftItems: cleanText(this.intake.items, 500), receptionPhotos: this.photoUrls, estimatedDate: this.intake.estimatedDate, mechanicId: mechanic?.id, assignedMechanic: mechanic?.name };
    const appointment = this.selectedOrder && this.selectedOrder.vehicleId === v.id && this.selectedOrder.status === 'recibido' ? this.selectedOrder : undefined;
    if (appointment) { this.saving = true; this.workshop.checkInOrder(appointment.id, { ...data, status: mechanic ? 'en_diagnostico' : 'recibido' }, (updated, error) => { this.saving = false; if (!updated) return this.notify('error', error || 'No se pudo guardar la ficha de recepción.'); this.finishCheckin(updated.id); }); return; }
    this.saving = true; this.workshop.addOrder({ clientId: v.ownerId, vehicleId: v.id, description: cleanText(this.intake.description, 500), status: mechanic ? 'en_diagnostico' : 'recibido', services: ['Diagnóstico inicial'], nextMaintenance: 'Por definir', ...data, recepcionistaId: this.workshop.currentUser()?.id }, (order, error) => { this.saving = false; if (!order) return this.notify('error', error || 'No se pudo registrar el ingreso.'); this.finishCheckin(order.id); });
  }
  private finishCheckin(orderId: number): void { this.notify('success', `Ficha creada con éxito. Ingreso #${orderId} registrado correctamente.`); this.selectedOrderId = orderId; this.checkinErrors = {}; this.checkinSummary = []; this.intake = { description: '', mileage: null, fuel: '1/2', damages: '', noDamages: false, notes: '', items: '', estimatedDate: '', mechanicId: 0, clientConfirmed: false }; this.photoUrls = []; this.checkinCompleted.set(orderId); }
  vehicleCount(clientId: number): number { return this.workshop.vehicles().filter(vehicle => vehicle.ownerId === clientId).length; }
  additionalTotal(orderId: number): number { return this.workshop.additionalWorks().filter(work => work.orderId === orderId && work.estado === 'APROBADO').reduce((total, work) => total + work.costoEstimado, 0); }
  saveQuote(order: WorkOrder): void { const errors: FieldErrors = {}; const amounts = [this.quote.parts, this.quote.labor, this.quote.other]; if (cleanText(this.quote.detail, 255).length < 5) errors.detail = 'El detalle debe tener al menos 5 caracteres.'; if (amounts.some(amount => !Number.isInteger(Number(amount)) || Number(amount) < 0)) errors.amounts = 'Los montos deben ser enteros no negativos.'; const total = amounts.reduce((sum, amount) => sum + Number(amount), 0); if (total <= 0) errors.total = 'El total debe ser mayor que cero.'; this.quoteErrors = errors; if (Object.keys(errors).length) return; const details: OrderQuote['detalles'] = [{ id: 0, cotizacionId: 0, tipo: 'REPUESTO' as const, descripcion: cleanText(this.quote.detail, 255), cantidad: 1, precioUnitario: Number(this.quote.parts), subtotal: Number(this.quote.parts) }, { id: 0, cotizacionId: 0, tipo: 'MANO_DE_OBRA' as const, descripcion: 'Mano de obra', cantidad: 1, precioUnitario: Number(this.quote.labor), subtotal: Number(this.quote.labor) }].filter(d => d.subtotal > 0); this.workshop.createQuoteVersion(order.id, total, { detalles: details, observaciones: cleanText(this.quote.detail, 255) }); this.workshop.updateOrderStatus(order.id, 'cotizacion_pendiente'); this.notify('success', 'Cotización enviada al Portal Cliente para aprobación.'); }
  approveQuote(order: WorkOrder, approved: boolean): void { if (!approved && cleanText(this.quote.rejectReason, 500).length < 3) { this.quoteErrors = { rejectReason: 'Indica el motivo del rechazo.' }; return; } const quote = this.workshop.quotes().find(item => item.orderId === order.id && item.estado === 'pendiente'); if (quote) this.workshop.quotes.update(items => items.map(item => item.id === quote.id ? { ...item, estado: approved ? 'aprobado' : 'rechazado', fechaRespuesta: new Date().toISOString(), aprobadoPor: this.clientName(order.clientId), medioRespuesta: this.quote.channel, motivoRechazo: approved ? undefined : cleanText(this.quote.rejectReason, 500) } : item)); this.workshop.respondToQuote(order.id, approved ? 'aprobado' : 'rechazado', { approvedBy: this.clientName(order.clientId), responseMethod: this.quote.channel, rejectReason: approved ? undefined : cleanText(this.quote.rejectReason, 500) }); this.notify('success', approved ? `Cotización aprobada por ${this.clientName(order.clientId)} vía ${this.quote.channel}.` : 'Cotización rechazada por el cliente.'); }
  advance(order: WorkOrder): void { const next: Record<string, WorkOrderStatus> = { recibido: 'en_diagnostico', en_diagnostico: 'cotizacion_pendiente', cotizacion_pendiente: 'en_reparacion', esperando_aprobacion: 'en_reparacion', en_reparacion: 'trabajo_terminado', trabajo_terminado: 'listo_para_entrega', listo_para_entrega: 'entregado' }; const target = next[this.workshop.normalizeStatus(order.status)]; if (target && !this.workshop.updateOrderStatus(order.id, target)) this.notify('error', 'La orden requiere aprobación de la cotización antes de continuar.'); }
  openDelivery(order: WorkOrder): void { this.deliveryOrderId = order.id; this.delivery = { receiverName: this.clientName(order.clientId), receiverRut: this.workshop.users().find(user => user.id === order.clientId)?.rut || '', approved: order.quoteStatus === 'aprobado', signed: false }; this.deliveryErrors = {}; }
  finishDelivery(): void { const order = this.workshop.orders().find(item => item.id === this.deliveryOrderId); const errors: FieldErrors = {}; if (!order || this.workshop.normalizeStatus(order.status) !== 'listo_para_entrega') errors.status = 'Solo se puede entregar una orden en estado “listo para entrega”.'; if (cleanText(this.delivery.receiverName, 100).length < 4) errors.name = 'Indica quién retira el vehículo.'; if (!validRut(this.delivery.receiverRut)) errors.rut = 'Ingresa un RUT válido de quien retira.'; if (!this.delivery.approved || order?.quoteStatus !== 'aprobado') errors.approved = 'La cotización debe estar aprobada o pagada.'; if (!this.delivery.signed) errors.signed = 'Se requiere la firma o conformidad de retiro.'; this.deliveryErrors = errors; if (Object.keys(errors).length || !order) return; this.workshop.deliverVehicleToClient(order.id); this.deliveryOrderId = 0; this.notify('success', `Entrega de la orden #${order.id} registrada.`); }
  confirmAppointment(order: WorkOrder): void { this.workshop.checkInOrder(order.id, { status: 'recibido' }); this.selectedOrderId = order.id; this.section = 'checkin'; this.selectedVehicleId = order.vehicleId; this.intake.description = order.description; this.notify('success', 'Llegada confirmada. Completa ahora la ficha de recepción.'); }
  receiveStock(): void {
    const partId = Number(this.stockReceipt.sparePartId); const quantity = Number(this.stockReceipt.quantity);
    if (!partId || !Number.isInteger(quantity) || quantity <= 0) { this.notify('error', 'Selecciona un repuesto y una cantidad entera mayor que cero.'); return; }
    this.saving = true;
    this.workshop.receiveSparePart(partId, quantity, cleanText(this.stockReceipt.supplier, 120), cleanText(this.stockReceipt.reference, 120), (part, error) => {
      this.saving = false;
      if (!part) { this.notify('error', error || 'No se pudo registrar la entrada de inventario.'); return; }
      this.stockReceipt = { sparePartId: 0, quantity: 1, supplier: '', reference: '' };
      this.notify('success', `Entrada registrada. Stock actual de ${part.name}: ${part.stock}.`);
    });
  }
  saveAppointment(): void { const errors: FieldErrors = {}; const v = this.workshop.vehicles().find(x => x.id === Number(this.appointment.vehicleId)); if (!v) errors.vehicle = 'Selecciona un vehículo.'; if (cleanText(this.appointment.description, 500).length < 5) errors.description = 'El motivo debe tener al menos 5 caracteres.'; if (!this.appointment.date || new Date(this.appointment.date).getTime() <= Date.now()) errors.date = 'La fecha y hora deben ser futuras.'; if (this.workshop.orders().some(order => order.status === 'solicitada' && order.appointmentAt && new Date(order.appointmentAt).getTime() === new Date(this.appointment.date).getTime())) errors.date = 'Ya existe una cita en ese horario.'; this.appointmentErrors = errors; if (Object.keys(errors).length || !v) return; this.saving = true; this.workshop.addOrder({ clientId: v.ownerId, vehicleId: v.id, description: cleanText(this.appointment.description, 500), status: 'solicitada', services: [], nextMaintenance: 'Por definir', appointmentAt: this.appointment.date }, (o, e) => { this.saving = false; if (!o) return this.notify('error', e || 'No se pudo crear la cita.'); this.appointment = { vehicleId: 0, description: '', date: '' }; this.notify('success', 'Cita agendada correctamente.'); }); }
  openClient(c?: User): void {
    const parts = cleanText(c?.name || '', 100).split(' ').filter(Boolean);
    this.client = c ? { id: c.id, name: c.name, firstName: parts.shift() || '', firstLastName: parts.shift() || '', secondLastName: parts.join(' '), email: c.email, rut: formatRut(c.rut || ''), phone: c.phone || '', alternatePhone: c.alternatePhone || '', dataConsent: Boolean(c.dataConsent) } : { id: 0, name: '', firstName: '', firstLastName: '', secondLastName: '', email: '', rut: '', phone: '', alternatePhone: '', dataConsent: false };
    this.clientErrors = {}; this.clientSummary = []; this.showClientModal = true;
  }
  formatClientRut(): void { this.client.rut = formatRut(this.client.rut); }
  saveClient(): void {
    const errors: FieldErrors = {};
    const firstName = cleanText(this.client.firstName, 50); const firstLastName = cleanText(this.client.firstLastName, 50); const secondLastName = cleanText(this.client.secondLastName, 50);
    const name = cleanText(`${firstName} ${firstLastName} ${secondLastName}`, 100); const email = cleanEmail(this.client.email); const rut = formatRut(this.client.rut);
    if (!validNamePart(firstName)) errors.firstName = 'El nombre debe tener al menos 2 letras y solo caracteres válidos.';
    if (!validNamePart(firstLastName)) errors.firstLastName = 'El primer apellido debe tener al menos 2 letras y solo caracteres válidos.';
    if (!validNamePart(secondLastName) || !validFullName(name)) errors.secondLastName = 'El segundo apellido debe tener al menos 2 letras y solo caracteres válidos.';
    if (!validRut(rut)) errors.rut = 'El RUT no es válido.'; if (this.clients.some(user => user.id !== this.client.id && cleanRut(user.rut || '') === cleanRut(rut))) errors.rut = 'El RUT ya está registrado.';
    if (!validChileanMobile(this.client.phone)) errors.phone = 'Usa un celular chileno de 9 dígitos iniciado en 9.'; if (this.client.alternatePhone && !validChileanMobile(this.client.alternatePhone)) errors.alternatePhone = 'El teléfono alternativo no es válido.';
    if (!validEmail(email)) errors.email = 'Ingresa un correo válido.'; if (this.clients.some(user => user.id !== this.client.id && cleanEmail(user.email) === email)) errors.email = 'El correo ya está registrado.';
    if (!this.client.dataConsent) errors.consent = 'Debes registrar el consentimiento de datos.';
    this.clientErrors = errors; this.clientSummary = Object.values(errors).filter((message): message is string => Boolean(message));
    if (this.clientSummary.length) { this.notify('error', `No se pudo guardar el cliente: ${this.clientSummary.join(' ')}`); return; }
    this.client = { ...this.client, name, firstName, firstLastName, secondLastName, email, rut }; this.saving = true;
    if (this.client.id) { this.workshop.updateClient(this.client.id, this.client); this.saving = false; this.showClientModal = false; return; }
    const password = this.password(); this.workshop.registerClient(name, email, password, (u, e) => { this.saving = false; if (!u) return this.notify('error', e || 'No se pudo crear el cliente.'); this.credentials.set({ email: u.email, password }); this.showClientModal = false; this.notify('success', 'Cliente creado con éxito.'); }, this.client);
  }
  openVehicle(v?: Vehicle): void { this.vehicle = v ? { ...v } : { id: 0, ownerId: this.clients.find(client => client.active !== false)?.id || 0, type: 'Auto', brand: '', model: '', plate: '', year: new Date().getFullYear() }; this.vehicleErrors = {}; this.showVehicleModal = true; }
  saveVehicle(): void { const errors: FieldErrors = {}; const plate = normalizePlate(this.vehicle.plate); if (!this.vehicle.ownerId) errors.owner = 'Selecciona el propietario.'; if (!validPlate(plate, this.vehicle.type)) errors.plate = 'La patente no corresponde al formato del tipo de vehículo.'; if (this.workshop.vehicles().some(item => item.id !== this.vehicle.id && normalizePlate(item.plate) === plate)) errors.plate = 'La patente ya está registrada.'; if (!cleanText(this.vehicle.brand, 50)) errors.brand = 'La marca es obligatoria.'; if (!cleanText(this.vehicle.model, 80)) errors.model = 'El modelo es obligatorio.'; if (!Number.isInteger(Number(this.vehicle.year)) || Number(this.vehicle.year) < 1950 || Number(this.vehicle.year) > new Date().getFullYear() + 1) errors.year = `El año debe estar entre 1950 y ${new Date().getFullYear() + 1}.`; this.vehicleErrors = errors; if (Object.keys(errors).length) return; const data = { ...this.vehicle, plate, brand: cleanText(this.vehicle.brand, 50), model: cleanText(this.vehicle.model, 80) }; this.saving = true; if (data.id) this.workshop.updateVehicle(data.id, data); else this.workshop.addVehicle(data, (_v, error) => { if (error) this.notify('error', error); }); this.saving = false; this.showVehicleModal = false; }
  copyCredentials(): void { const c = this.credentials(); if (c) navigator.clipboard?.writeText(`Correo: ${c.email}\nClave temporal: ${c.password}`); } private notify(type: 'success' | 'error', text: string): void { this.messageType = type; this.message = text; } private password(): string { return `Nexus${Math.random().toString(36).slice(2, 7)}${Math.floor(10 + Math.random() * 90)}`; }
}
